### ISSUE TITLE
its not an issue, but i cant give a comment on your website

### ISSUE THREAD

**Issue by sultan775** [h-c-c/Seven_Segment_Pixel#3]
hi,its a nice post, your library very easy to use, i made a rgb clock using your library here https://youtu.be/TmzvhchDtOE

and i hope you dont mind to give me permission about it, i modified your librarry for six segment dispay, here the display look like https://youtu.be/exU-CR7pgeg
 thanks in advadnce, if you dont like it send me a email please.. 
shasibuan03@gmail.com

**Comment by h-c-c** [comment]
Thanks for the note.  LOVE IT.  Especially the six segment.  It looks more like handwriting.

My blog is hammered with spam comments. So even if you were able to comment I might not get to approving it for some time.  

Thanks for sharing your project, and glad you found this library useful!

Best,
Peter
